"""empty message

Revision ID: 330215d8bf41
Revises: a4f70aadacc4
Create Date: 2020-11-19 12:16:21.700913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330215d8bf41'
down_revision = 'a4f70aadacc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'venue_name')
    op.drop_column('Show', 'artist_image_link')
    op.drop_column('Show', 'artist_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('artist_image_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('venue_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
