"""empty message

Revision ID: a4f70aadacc4
Revises: dc5beb616179
Create Date: 2020-11-19 12:11:28.420001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f70aadacc4'
down_revision = 'dc5beb616179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'venue_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'venue_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
